Repository realponto-project/stock-rp-front, pull requests merged in 2020-12, with the labels that each got.

#44 Refactor/user
  src/components/SideBar/index.js
  src/containers/User/AddUser/index.js
  src/containers/User/AddUser/style.module.css
  src/pages/Cadastros/NovoUsuario/UsuarioContainer/index.css
  src/pages/Cadastros/NovoUsuario/UsuarioContainer/index.js
  src/pages/Cadastros/NovoUsuario/index.js
  src/pages/User/AddUser/index.js
  src/pages/User/AddUser/userSpec.js
  src/pages/User/index.js
  src/pages/index.js
  src/stories/containers/User/AddUser/index.js
  src/utils/permissions.js
Labels: enhancement, front, refactor

#46 Refactor/technician
  .eslintrc.json
  .prettierrc
  .storybook/preview.js
  src/components/SideBar/index.js
  src/containers/Technician/AddTechinician/index.js
  src/containers/Technician/AddTechinician/style.module.css
  src/index.js
  src/pages/Cadastros/NovoTecnico/TecnicoContainer/index.css
  src/pages/Cadastros/NovoTecnico/TecnicoContainer/index.js
  src/pages/Cadastros/NovoTecnico/TecnicoContainer/validators.js
  src/pages/Cadastros/NovoTecnico/index.js
  src/pages/Gerenciar/GerenciarTecnico/GTecnicoContainer/index.js
  src/pages/Reservas/Romaneio antigo/TecnicoContainer/index.js
  src/pages/Technician/AddTechnician/carSpec.js
  src/pages/Technician/AddTechnician/index.js
  src/pages/Technician/AddTechnician/technicianSpec.js
  src/pages/Technician/index.js
  src/pages/index.js
  src/services/tecnico.js
  src/stories/containers/Technician/AddTechnician/index.js
  src/utils/index.js
  src/utils/validators.js
Labels: front, refactor

#60 Refact/product container
  src/containers/Product/AddProduct/index.js
  src/containers/Product/AddProduct/style.module.css
  src/pages/Product/AddProduct/index.js
  src/pages/Product/AddProduct/productSpec.js
  src/routes/index.css
  src/stories/containers/Product/AddProduct/index.js
  src/stories/containers/Product/ManageProducts/index.js
  src/stories/containers/Products/AddProducts/index.js
  src/utils/productSpec.js
Labels: debit-technician, enhancement, front, refactor
